application:
  title: @project.name@
  version: @project.version@

bookshelf:
  owner: Someone
  isbn-lookup:
    url: https://example.org/isbn
    api-key: secret

spring:
  datasource:
    hikari:
      maximum-pool-size: 1
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  sql:
    init:
      mode: always

management:
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"
